name: Cargo Build & Test
permissions:
  contents: read

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:

    - name : Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      run: |
        rustup update ${{ matrix.toolchain }}
        rustup override set ${{ matrix.toolchain }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Lint
      run: |
        rustup component add clippy
        cargo clippy --all-targets --all-features --verbose

    - name: Check formatting
      run: |
        rustup component add rustfmt
        cargo fmt --all --verbose --check

    - name: Generate documentation
      run: cargo doc --lib --no-deps --all-features --verbose

      