name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : Checkout
      uses: actions/checkout@v4
    - name: Set up Rust
      run: rustup toolchain install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run linting
      # run: cargo clippy --all-targets --all-features --verbose -- -W clippy::pedantic -D warnings 
      run: cargo clippy --all-targets --all-features --verbose -- -W clippy::pedantic
